### ISSUE TITLE
Calibration against CM100 was done too fine, see sited article about deviation at sub 500um grind size on CM100+

### ISSUE THREAD

**Issue by skatcat31** [juztins-lab/roast-meter#10]
I've also noticed this on my OMNI; if the ground is too fine, there can be a 20+ Agtron reading jump.

It is recommended to grind to SCA cupping size(roughly 750um-800um for the majority) for the CM100/+ and the OMNI.

I would suggest a recalibration process for this reader so it can trend properly.

relevant section: https://artisan-roasterscope.blogspot.com/2023/03/understanding-roast-color.html#:~:text=is%20kept%20constant.-,Particle%20Size,-The%20amount%20of

**Comment by juztins-lab** [comment]
Hi,

Thank you for your feedback, we are aware of this scenario, but it does not fall in the use case we intended for the device.
We have a section in regard to the agtron scale in the documentation (https://github.com/juztins-lab/roast-meter/wiki/Roast-Meter-User's-Guide#agtron-gourmet-formula), check the note)

If you wish to align the reading to agtron (using SCA sample prep) using the tonino plotting tool, feel free to change the "f()" function in the arduino code. We had a debate on this topic and decided not to.
