### ISSUE TITLE
code installation software not working

### ISSUE THREAD

**Issue by giangian1** [juztins-lab/roast-meter#12]
hi guys, i am trying to install the software into my device but isn t working, I am following all the steps but nothing.  Is there a video to follow instructions?

**Comment by giangian1** [comment]
it keep saying: Compilation error: SFE_MicroOLED.h: No such file or directory

**Comment by wadeduvall** [comment]
Did you add the libraries for the OLED as described [here](https://learn.sparkfun.com/tutorials/installing-an-arduino-library)?

**Comment by giangian1** [comment]
Yes sorted, thanks for asking
