### ISSUE TITLE
Progress bar in loading mode

### ISSUE THREAD

**Issue by beanoccio** [juztins-lab/roast-meter#13]
Hello

I built the Roast Meter in the battery version. Everything seems to work as planned.
I can measure the tanning progress of the skin after a day in the mountains or at the beach.
It would be nice and helpful if there was a progress indicator for the charging mode.

![image](https://github.com/juztins-lab/roast-meter/assets/132497527/5ae88d27-28bc-4f76-86d6-4af91eb8ab4b)

**Comment by juztins-lab** [comment]
Hi, thank you!
Unfortunately the hardware does not support it, additional steps is required and it raises complexity and probably the size a bit.
The yellow led indicates if its charging and it closes when its full.
Also battery lifetime is a couple of months on my usage of about 10 measurements a week.
