### ISSUE TITLE
Instructions for calibration with sodium bicarbonate unclear

### ISSUE THREAD

**Issue by wadeduvall** [juztins-lab/roast-meter#15]
Instructions state "Apply a heaping amount to the sensor so that little red light shows through." Depending on what little means, I can get a variety of readings. If I completely block it out such that i can't see any red light, I get ~260. Is this the value I should be calibrating off of? If I adjust it so that a tiny bit of red light escapes, then I get almost exactly 230.  But it varies wildly based on how thick exactly the bed of bicarb is. If you truly mean no light, I would recommend updating it to read "Apply a heaping amount to the sensor so that no red light shines through"

**Comment by Brewzologist** [comment]
Modified manual to say that no light passes thru.
