### ISSUE TITLE
LED Light is outside the glass circle.

### ISSUE THREAD

**Issue by acarr123** [juztins-lab/roast-meter#17]
I recently built my roast meter but the led light is shining outside the sensor area so I’m not sure how to calibrate it since the coffee doesn't cover the led light.
![IMG_0587](https://github.com/user-attachments/assets/cfc05563-03c2-474a-824d-afe6edffa4ab)

**Comment by juztins-lab** [comment]
hi, led is IR, you won't see it, the other one is the power led, you can ignore it. Please follow the calibration instructions as per the guide, using bicarb and adjusting the ledBrightness variable till you read 230.

PS. I removed mentions of the red light from the documentation, that was an old reference when the sensor red light led was enabled, it is not the case anymore.
