### ISSUE TITLE
Suggested updates to roast_meter.ino

### ISSUE THREAD

**Issue by Brewzologist** [juztins-lab/roast-meter#2]
1) Cleaned up unused code that was commented out and/or not functional.
-- Rationale: make code easier to read and maintain.

2) Modified loop() to call getIR() one time per iteration so each rLevel is being tested AND displayed. 
-- Rationale: each call to getIR() removes a sensor result from a FIFO queue.  Each iteration in loop() calls getIR(), tests it, then calls GetIR() again to display, so only every other sensor result is displayed.

3) Removed intToHex() function.  
-- Rationale: you can assign a value directly to ledBrightness.  no need for this function.

4) Added ledBrightnessOffset calibration variable.  
-- Rationale: using ledBrightness alone, which changes LED amplitude, is too coarse for calibration.  (e.g. changing it by +/- 1 causes as much as +6-7 points of Agtron reading change.)  So, created an additional variable affecting the Agtron conversion formula. This approach first allows calibration for sensor hardware differences, and then calibrates the Agtron conversion formula to a desired target value to addresss any remaining inconsistencies.  See comments in code.

5) Changed values passed to particleSensor.setup().  These are experimental but I'm not sure a high sample frequency is needed for measuring coffee vs the original intended use of the MAX30301 for HR/SPO2.
-- Rationale: optimizing MAX30101 sensor settings for coffee measurements.

6) After calling particleSensor.setup(), added overrides to specifically turn off all LED's and slots on the MAX30101 except for the IR LED.  
-- Rationale: the code only calls getIR(), and in testing the red LED had no effect on the values returned by getIR() so turned it off.  Also disabled slots for red and green LEDs. Purpose is to optimize the MAX30101 LED settings for coffee measurements.

See code changes here:
[roast_meter_ino.zip](https://github.com/juztins-lab/roast-meter/files/11193078/roast_meter_ino.zip)

**Comment by juztins-lab** [comment]
1,2,3 - OK
4. The idea of fine tuning is great and can be added later down the line, tho the implementation needs to offset the IR value not the converted result since the deviation becomes increasingly further from the scale in question.
5,6 Testing and calibration was done with the red led and proved better results, will need to revise this but at the moment this will not change, adjusted sampleRate and average to 50 and 4.
