### ISSUE TITLE
Bottom v.2.0.3mf contains no models in Cura

### ISSUE THREAD

**Issue by wongcoder** [juztins-lab/roast-meter#3]
![image](https://user-images.githubusercontent.com/16981265/230964005-29e703e1-2682-411c-8962-ba145a92c65e.png)
On attempting to open the .3mf, it will result in an error. 

This isn't a major issue, as the other .stl file exists, but it is something to note.

**Comment by nsolling** [comment]
Hi, I will check this.
There is still major work ongoing with the case - Although the version we have now is totally usable a few users are working on a more sturdy design.
I will just wait for that work to materialize before starting to fix up the potential issue.
BTw. the 3mf works fine in other slicers as per my tests.

**Comment by nsolling** [comment]
Have removed the 3mf file and only publishes STL file as well as Fusion360 file now
