### ISSUE TITLE
Should we round the calculated Agtron result?

### ISSUE THREAD

**Issue by Brewzologist** [juztins-lab/roast-meter#6]
The way the Agtron conversion function f() is written, any decimal places are truncated.  e.g. both 88.1 and 88.9 return 88 from this function.  Is this intended?  

I added the round() function before returning from f() so it will round the Agtron result to the closest integer. example:

return round((x - (intersectionPoint - x) * deviation) + ledBrightnessOffset);

**Comment by juztins-lab** [comment]
Round is good.
Will apply the suggestion, it will not affect the current precision and allowed variation of 1-3 levels for the same roast level.
