### ISSUE TITLE
Does the OLED area expect a glass slide?

### ISSUE THREAD

**Issue by mrnoisytiger** [juztins-lab/roast-meter#9]
I'm not seeing this in the instructions, but does the LCD/OLED area expect a glass cover slide? Without one, it seems like the screen is quite far away from the actual top of the tray.

**Comment by nsolling** [comment]
No, that is not the design - You are correct, that the actual display is a seated a bit low, but it does not have any practical impact.
I know that some users have modified the original cas design, but personally I do not see the need for it.

**Comment by nsolling** [comment]
Closing after clarification
